### ISSUE TITLE
Question: How to "backtrack"?

### ISSUE THREAD

**Issue by yohgen** [sxzz/unplugin-ast#50]
Hi. This is not a bug report, but rather a question. Forgive me if my question is misplaced, this is the first time I'm working with transpilation process.

Is "backtracking" (i.e. going up the tree/changing branches) a possibility with `unplugin-ast`? I wonder if this library can help me implement this:

I want to search for a call expression of a specific function, and if the conditions are met, inline the function body to speed up the code (if they are not met, then everything is left as is). One of the conditions is that the second argument should be a static array. However, a reference to that array can be assigned to a variable prior to the function invocation, and I need to check for such a possibility, and for that I need to track back to the assignment.

**Comment by sxzz** [comment]
`unplugin-ast` is like a simplified Babel plugin, so it will not consider complex features.

You can try to [write a Babel plugin](https://babeljs.io/docs/plugins) for advanced usage.

**Comment by yohgen** [comment]
@sxzz I see, thank you for the pointer!
